# Generated by Django 4.2.6 on 2023-10-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_year', models.CharField(max_length=4)),
                ('rating', models.CharField(max_length=10)),
                ('runtime', models.CharField(max_length=10)),
                ('genre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('director', models.CharField(max_length=255)),
                ('stars', models.TextField()),
            ],
        ),
    ]
