# Generated by Django 4.2.6 on 2023-10-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_movie_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
