# Generated by Django 4.2.6 on 2023-10-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_movie_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
