# Generated by Django 4.2.6 on 2023-10-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_movie_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_img',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_url',
        ),
    ]
